services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "wowsims-to-commands"
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./:/app
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "4"

#networks
networks:
  app-network:
    driver: bridge
